# Generated by Django 5.1 on 2024-10-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=120, null=True, verbose_name="Title"),
        ),
    ]
