# Generated by Django 5.1 on 2024-10-16 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="abstract",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="adviser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_adviser",
                to="project.approved_adviser",
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="project_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.approvedprojectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="adviser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.approved_adviser",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Project Type"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="proponents",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.project_group",
            ),
        ),
    ]
