# Generated by Django 5.1 on 2024-10-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_defense_application_abstract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="comments",
            field=models.TextField(null=True),
        ),
    ]
