# Generated by Django 5.1 on 2024-10-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_project_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
