# Generated by Django 5.1 on 2024-10-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_alter_project_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_group",
            name="group_name",
        ),
    ]
