# Generated by Django 5.1 on 2024-10-20 23:42

import django.db.models.manager
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_remove_project_group_group_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approved_student",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("project.student",),
            managers=[
                ("approved_panel", django.db.models.manager.Manager()),
                ("objects", project.models.AppUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="panel",
            field=models.ManyToManyField(
                blank=True,
                related_name="application_panel",
                to="project.approved_panel",
            ),
        ),
    ]
