# Generated by Django 5.1 on 2024-10-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_approved_student_alter_defense_application_panel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="design_defense",
        ),
        migrations.RemoveField(
            model_name="project",
            name="final_defense",
        ),
        migrations.RemoveField(
            model_name="project",
            name="preliminary_defense",
        ),
        migrations.RemoveField(
            model_name="project",
            name="proposal_defense",
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal Defense"),
                            ("design", "Design Defense"),
                            ("preliminary", "Preliminary Defense"),
                            ("final", "Final Defense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
