# Generated by Django 5.1 on 2024-10-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_remove_project_design_defense_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectphase",
            old_name="status",
            new_name="verdict",
        ),
    ]
