# Generated by Django 5.1 on 2024-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_rename_status_projectphase_verdict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectphase",
            name="verdict",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
