# Generated by Django 5.1 on 2024-10-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_alter_projectphase_verdict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectphase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal Defense"),
                    ("design", "Design Defense"),
                    ("preliminary", "Preliminary Defense"),
                    ("final", "Final Defense"),
                ],
                default="proposal",
                max_length=20,
            ),
        ),
    ]
