# Generated by Django 5.1 on 2024-10-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_alter_projectphase_phase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="submission_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="verdict",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("accepted_with_revisions", "Accepted with Revisions"),
                    ("redefense", "Re-Defense"),
                    ("not_accepted", "Not Accepted"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
