# Generated by Django 5.1 on 2024-10-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_alter_defense_application_submission_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project_group",
            name="adviser",
        ),
    ]
