# Generated by Django 5.1 on 2024-10-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_remove_project_group_adviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_group",
            name="approved_by_students",
            field=models.ManyToManyField(
                blank=True, related_name="approved_project_groups", to="project.student"
            ),
        ),
        migrations.AddField(
            model_name="project_group",
            name="pending_proponents",
            field=models.ManyToManyField(
                blank=True, related_name="pending_project_groups", to="project.student"
            ),
        ),
    ]
