# Generated by Django 5.1 on 2024-10-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_project_group_approved_by_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_group",
            name="approved",
            field=models.BooleanField(
                default=False, verbose_name="All Students Approved"
            ),
        ),
    ]
