# Generated by Django 5.1 on 2024-10-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_alter_project_group_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_group",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to="project.student",
                verbose_name="Project Group Creator",
            ),
        ),
    ]
