# Generated by Django 5.1 on 2024-10-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_alter_project_group_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project_group",
            old_name="owner",
            new_name="creator",
        ),
    ]
