# Generated by Django 5.1 on 2024-10-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_group",
            name="declined_proponents",
            field=models.ManyToManyField(
                blank=True, related_name="declined_groups", to="project.student"
            ),
        ),
    ]
