# Generated by Django 5.1 on 2024-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_project_group_declined_proponents"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_group",
            name="join_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have requested to join this group",
                related_name="requested_groups",
                to="project.student",
            ),
        ),
    ]
