# Generated by Django 5.1 on 2024-11-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_project_group_join_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_group",
            name="declined_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have been declined to join this group",
                related_name="declined_requests",
                to="project.student",
            ),
        ),
    ]
