# Generated by Django 5.1 on 2024-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_project_group_declined_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="project_group",
            name="requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have sent join requests to this group",
                related_name="sent_requests",
                to="project.student",
            ),
        ),
    ]
