# Generated by Django 5.1 on 2024-11-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_project_group_requests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="approved",
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
