# Generated by Django 5.1 on 2024-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_remove_project_approved_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinatorprofile",
            name="coordinator_id",
        ),
        migrations.AddField(
            model_name="coordinatorprofile",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
