# Generated by Django 5.1 on 2024-11-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_remove_coordinatorprofile_coordinator_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoordinatorProfile",
            new_name="Coordinator_User",
        ),
    ]
