# Generated by Django 5.1 on 2024-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0025_rename_coordinatorprofile_coordinator_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coordinator_User",
            new_name="CoordinatorProfile",
        ),
    ]
