# Generated by Django 5.1 on 2024-11-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_rename_coordinator_user_coordinatorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
    ]
