# Generated by Django 5.1 on 2024-11-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_appuser_is_current"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultyprofile",
            name="faculty_id",
        ),
    ]
