# Generated by Django 5.1 on 2024-11-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_remove_facultyprofile_faculty_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
