# Generated by Django 5.1 on 2024-11-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_alter_appuser_is_current"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="is_current",
        ),
    ]
