# Generated by Django 5.1 on 2024-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_remove_appuser_is_current"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
