# Generated by Django 5.1 on 2024-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0033_appuser_is_current_coordinator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinatorprofile",
            name="is_current",
        ),
    ]
