# Generated by Django 5.1 on 2024-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0034_remove_coordinatorprofile_is_current"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectphase",
            options={"get_latest_by": "date"},
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal Defense"),
                    ("design", "Graded 1 or Design Defense"),
                    ("preliminary", "Preliminary Defense"),
                    ("final", "Grade 2 or Final Defense"),
                ],
                default="proposal",
                max_length=20,
            ),
        ),
    ]
