# Generated by Django 5.1 on 2024-11-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0035_alter_projectphase_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectphase",
            options={},
        ),
    ]
