# Generated by Django 5.1 on 2024-11-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_alter_projectphase_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="panel",
            field=models.ManyToManyField(
                blank=True,
                related_name="capplication_panel",
                to="project.approved_panel",
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="title",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal Title"),
                    ("design", "Design Title"),
                    ("preliminary", "Preliminary Title"),
                    ("final", "Final Title"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
