# Generated by Django 5.1 on 2024-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0037_alter_defense_application_panel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="title",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal Defense"),
                    ("design", "Graded 1 Defense"),
                    ("preliminary", "Preliminary Defense"),
                    ("final", "Graded 2 Defense"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
