# Generated by Django 5.1 on 2024-11-08 09:58

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_alter_defense_application_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Not_ApprovedProject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("project.project",),
            managers=[
                ("not_approved_project", django.db.models.manager.Manager()),
            ],
        ),
    ]
