# Generated by Django 5.1 on 2024-11-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0039_not_approvedproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defense_application",
            name="document",
        ),
        migrations.AddField(
            model_name="defense_application",
            name="adviser_confirmation",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/adviser_confirmation"
            ),
        ),
        migrations.AddField(
            model_name="defense_application",
            name="manuscript",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/manuscript"
            ),
        ),
        migrations.AddField(
            model_name="defense_application",
            name="payment_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/payment_receipt"
            ),
        ),
        migrations.AddField(
            model_name="defense_application",
            name="revision_form",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/revision_form"
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
