# Generated by Django 5.1 on 2024-11-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0042_alter_defense_application_adviser_confirmation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="manuscript",
            field=models.FileField(null=True, upload_to="submissions/manuscript"),
        ),
    ]
