# Generated by Django 5.1 on 2024-11-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_alter_defense_application_manuscript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="adviser_confirmation",
            field=models.FileField(
                null=True, upload_to="submissions/adviser_confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="payment_receipt",
            field=models.FileField(null=True, upload_to="submissions/payment_receipt"),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="revision_form",
            field=models.FileField(null=True, upload_to="submissions/revision_form"),
        ),
    ]
