# Generated by Django 5.1 on 2024-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0046_alter_defense_application_adviser_confirmation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation", "Group Invitation"),
                    ("accepted", "Group Invitation Accepted"),
                    ("rejected", "Group Invitation Rejected"),
                    ("group_complete", "Group Update"),
                    ("leave_group", "Group Update"),
                ],
                max_length=20,
            ),
        ),
    ]
