# Generated by Django 5.1 on 2024-11-10 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0048_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project_group",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INVITATION", "Group Invitation"),
                    ("ACCEPTED", "Accepted Group Invitation "),
                    ("REJECTED", "Rejected Group Invitation"),
                    ("GROUP_COMPLETE", "Group Update"),
                    ("LEAVE_GROUP", "Group Update"),
                    ("ROLE_CHANGE", "New Coordinator"),
                ],
                max_length=20,
            ),
        ),
    ]
