# Generated by Django 5.1 on 2024-11-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0049_alter_notification_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INVITATION", "Group Invitation"),
                    ("ACCEPTED", "Accepted Group Invitation "),
                    ("REJECTED", "Rejected Group Invitation"),
                    ("GROUP_COMPLETE", "Group Update"),
                    ("LEAVE_GROUP", "Group Update"),
                    ("ROLE_CHANGE", "New Coordinator"),
                    ("ROLE_TRANSFER", "Leader Role Transfer"),
                    ("NEW_MEMBER", "New Member Added"),
                    ("ADDED_TO_GROUP", "You have been added to a group"),
                ],
                max_length=20,
            ),
        ),
    ]
