# Generated by Django 5.1 on 2024-11-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0052_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INVITATION", "Group Invitation"),
                    ("ACCEPTED", "Accepted Group Invitation "),
                    ("REJECTED", "Rejected Group Invitation"),
                    ("GROUP_COMPLETE", "Group Completion"),
                    ("LEAVE_GROUP", "Left Group"),
                    ("ROLE_CHANGE", "New Coordinator"),
                    ("ROLE_TRANSFER", "Leader Role Transfer"),
                    ("NEW_MEMBER", "New Member Added"),
                    ("ADDED_TO_GROUP", "You have been added to a group"),
                    ("DECLINED_JOIN_REQUEST", "Join Request Declined"),
                    ("JOIN_REQUEST", "Join Request"),
                    ("JOIN_REQUEST_CANCELLED", "Join Request Cancelled"),
                    ("VERDICT", "Verdict"),
                    ("SUBMITTED_DEFENSE_APPLICATION", "[Defense Application]"),
                ],
                max_length=50,
            ),
        ),
    ]
