# Generated by Django 5.1 on 2024-11-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0056_alter_project_group_approved_by_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project_group",
            name="approved_by_students",
            field=models.ManyToManyField(
                blank=True, related_name="approved_project_groups", to="project.student"
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_groups",
                to="project.student",
                verbose_name="Project Group Creator",
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="declined_proponents",
            field=models.ManyToManyField(
                blank=True, related_name="declined_groups", to="project.student"
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="declined_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have been declined to join this group",
                related_name="declined_requests",
                to="project.student",
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="join_requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have requested to join this group",
                related_name="requested_groups",
                to="project.student",
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="pending_proponents",
            field=models.ManyToManyField(
                blank=True, related_name="pending_project_groups", to="project.student"
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="proponents",
            field=models.ManyToManyField(
                blank=True, related_name="project_proponents", to="project.student"
            ),
        ),
        migrations.AlterField(
            model_name="project_group",
            name="requests",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students who have sent join requests to this group",
                related_name="sent_requests",
                to="project.student",
            ),
        ),
    ]
