# Generated by Django 5.1 on 2024-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0057_alter_project_group_approved_by_students_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INVITATION", "Group Invitation"),
                    ("ACCEPTED", "Accepted Group Invitation "),
                    ("REJECTED", "Rejected Group Invitation"),
                    ("GROUP_COMPLETE", "Group Completion"),
                    ("GROUP_FINALIZED", "Group Finalization"),
                    ("LEAVE_GROUP", "Left Group"),
                    ("ROLE_CHANGE", "New Coordinator"),
                    ("ROLE_TRANSFER", "Leader Role Transfer"),
                    ("NEW_MEMBER", "New Member Added"),
                    ("ADDED_TO_GROUP", "You have been added to a group"),
                    ("DECLINED_JOIN_REQUEST", "Join Request Declined"),
                    ("JOIN_REQUEST", "Join Request"),
                    ("JOIN_REQUEST_CANCELLED", "Join Request Cancelled"),
                    ("VERDICT", "Verdict"),
                    ("PROJECT_ACCEPTED", "Project Accepted"),
                    ("PROJECT_REJECTED", "Project Rejected"),
                    ("SUBMITTED_DEFENSE_APPLICATION", "Defense Application"),
                    ("PANELIST_SELECTED", "Panelist Selected"),
                    ("MEMBER_REMOVAL", "Member Removed"),
                    ("ADVISER_ELIGIBILITY", "Adviser Eligibility"),
                    ("PANELIST_ELIGIBILITY", "Panelist Eligibility"),
                    ("COMMENTS_UPDATED", "Comments Updated"),
                    ("NEW_PROJECT_PROPOSAL", "New Project Proposal"),
                    ("PANELIST_DECLINE", "Panelist Decline"),
                    ("PANELIST_SELECTED", "Panelist Selected"),
                ],
                max_length=50,
            ),
        ),
    ]
