# Generated by Django 5.1 on 2024-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0058_alter_notification_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project_Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("faculty_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
