# Generated by Django 5.1 on 2024-11-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0059_project_idea"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project_idea",
            old_name="text",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="project_idea",
            old_name="faculty_name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="project_idea",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.faculty",
            ),
        ),
    ]
