# Generated by Django 5.1 on 2024-11-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0060_rename_text_project_idea_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
