# Generated by Django 5.1 on 2024-11-13 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0061_notification_redirect_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="adviser",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.faculty",
            ),
        ),
    ]
