# Generated by Django 5.1 on 2024-11-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0064_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectphase",
            name="phase_type",
            field=models.CharField(
                choices=[
                    ("proposal", "Proposal Defense"),
                    ("design", "Graded Defense 1"),
                    ("preliminary", "Preliminary Defense"),
                    ("final", "Grade 2 or Final Defense"),
                ],
                default="proposal",
                max_length=20,
            ),
        ),
    ]
