# Generated by Django 5.1 on 2024-11-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0066_alter_projectphase_phase_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_type", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_phases",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
