# Generated by Django 5.1 on 2024-11-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0067_customprojectphase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom_Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Custom Defense Set", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "phases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_sets",
                        to="project.projectphase",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_phases",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CustomProjectPhase",
        ),
    ]
