# Generated by Django 5.1 on 2024-11-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0068_custom_phase_delete_customprojectphase"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Custom Defense Set", max_length=100),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("phase_order", models.IntegerField(default=0)),
                (
                    "phases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_sets",
                        to="project.projectphase",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_phases",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["phase_order"],
            },
        ),
        migrations.DeleteModel(
            name="Custom_Phase",
        ),
    ]
