# Generated by Django 5.1 on 2024-11-19 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0069_customprojectphase_delete_custom_phase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="eligility_deficiencies",
            new_name="deficiencies",
        ),
    ]
