# Generated by Django 5.1 on 2024-11-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0070_rename_eligility_deficiencies_appuser_deficiencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="verdict",
            field=models.CharField(max_length=50, null=True, verbose_name="Verdict"),
        ),
    ]
