# Generated by Django 5.1 on 2024-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0071_notification_verdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="student_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
