# Generated by Django 5.1 on 2024-11-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0073_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomProjectPhase",
            new_name="CustomPhaseGroup",
        ),
    ]
