# Generated by Django 5.1 on 2024-11-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0074_rename_customprojectphase_customphasegroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defense_phases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, null=True, verbose_name="Custom Phase Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal Defense"),
                            ("design", "Graded Defense 1"),
                            ("preliminary", "Preliminary Defense"),
                            ("final", "Graded Final Defense"),
                        ],
                        default="proposal",
                        max_length=20,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("accepted_with_revisions", "Accepted with Revisions"),
                            ("redefense", "Re-Defense"),
                            ("not_accepted", "Not Accepted"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="defense_phases",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.defense_phases",
            ),
        ),
        migrations.AddField(
            model_name="defense_phases",
            name="phases",
            field=models.ManyToManyField(
                blank=True, related_name="custom_sets", to="project.phase"
            ),
        ),
    ]
