# Generated by Django 5.1 on 2024-11-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0075_defense_phases_phase_project_defense_phases_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="defense_phases",
        ),
        migrations.CreateModel(
            name="Defense_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, null=True, verbose_name="Custom Phase Name"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "phases",
                    models.ManyToManyField(
                        blank=True, related_name="custom_sets", to="project.phase"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="defense_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.defense_order",
            ),
        ),
        migrations.DeleteModel(
            name="Defense_phases",
        ),
    ]
