# Generated by Django 5.1 on 2024-11-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0076_remove_project_defense_phases_defense_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defense_order",
            name="phases",
        ),
        migrations.CreateModel(
            name="DefenseOrderPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_order", models.PositiveIntegerField()),
                (
                    "defense_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defense_order_phases",
                        to="project.defense_order",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defense_order_phases",
                        to="project.phase",
                    ),
                ),
            ],
            options={
                "ordering": ["phase_order"],
                "unique_together": {("defense_order", "phase")},
            },
        ),
    ]
