# Generated by Django 5.1 on 2024-11-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0077_remove_defense_order_phases_defenseorderphase"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
