# Generated by Django 5.1 on 2024-11-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0078_phase_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="defense_order",
        ),
        migrations.RemoveField(
            model_name="defenseorderphase",
            name="defense_order",
        ),
        migrations.AlterUniqueTogether(
            name="defenseorderphase",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="defenseorderphase",
            name="phase",
        ),
        migrations.CreateModel(
            name="CustomPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_name", models.CharField(max_length=100)),
                ("phase_order", models.PositiveIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_phases",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["phase_order"],
            },
        ),
        migrations.DeleteModel(
            name="CustomPhaseGroup",
        ),
        migrations.DeleteModel(
            name="Defense_order",
        ),
        migrations.DeleteModel(
            name="DefenseOrderPhase",
        ),
        migrations.DeleteModel(
            name="Phase",
        ),
    ]
