# Generated by Django 5.1 on 2024-11-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0079_remove_project_defense_order_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomPhase",
        ),
    ]
