# Generated by Django 5.1 on 2024-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0081_projectphase_first_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectphase",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
