# Generated by Django 5.1 on 2024-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0082_alter_projectphase_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectphase",
            name="first_phase",
        ),
    ]
