# Generated by Django 5.1 on 2024-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0083_remove_projectphase_first_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectphase",
            name="first_phase",
            field=models.BooleanField(default=False),
        ),
    ]
