# Generated by Django 5.1 on 2024-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0084_projectphase_first_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="color",
            field=models.CharField(default="#007BFF", max_length=7),
        ),
    ]
