# Generated by Django 5.1 on 2025-01-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0085_appuser_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="static/images/default_pic.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
