# Generated by Django 5.1 on 2025-01-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0089_alter_appuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
