# Generated by Django 5.1 on 2025-01-07 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0092_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="student",
        ),
        migrations.AddField(
            model_name="skill",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
