# Generated by Django 5.1 on 2025-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0094_predefinedskill_userskill_delete_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="appuser",
            name="skills",
            field=models.ManyToManyField(
                related_name="user_skills", to="project.skill"
            ),
        ),
    ]
