# Generated by Django 5.1 on 2025-01-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0095_skill_appuser_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
