# Generated by Django 5.1 on 2025-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0096_appuser_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_proponents",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of students allowed per project group",
                    ),
                ),
            ],
        ),
    ]
