# Generated by Django 5.1 on 2025-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0097_projectgroupsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="user_skills", to="project.skill"
            ),
        ),
    ]
