# Generated by Django 5.1 on 2025-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0098_alter_appuser_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="skills",
        ),
        migrations.AddField(
            model_name="appuser",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
