# Generated by Django 5.1 on 2025-01-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0099_remove_appuser_skills_appuser_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userskill",
            name="predefined_skill",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="user",
        ),
        migrations.DeleteModel(
            name="PredefinedSkill",
        ),
        migrations.DeleteModel(
            name="UserSkill",
        ),
    ]
