# Generated by Django 5.1 on 2025-01-18 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0101_project_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
