# Generated by Django 5.1 on 2025-01-18 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0102_delete_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
