# Generated by Django 5.1 on 2025-01-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0103_appuser_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="adviser_confirmation",
            field=models.ImageField(
                null=True, upload_to="submissions/adviser_confirmation"
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="manuscript",
            field=models.FileField(null=True, upload_to="submissions/manuscript"),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="payment_receipt",
            field=models.ImageField(null=True, upload_to="submissions/payment_receipt"),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="revision_form",
            field=models.FileField(null=True, upload_to="submissions/revision_form"),
        ),
    ]
