# Generated by Django 5.1 on 2025-01-19 21:03

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0105_alter_defense_application_adviser_confirmation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_application",
            name="adviser_confirmation",
            field=models.FileField(
                null=True, upload_to=project.models.submission_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="manuscript",
            field=models.FileField(
                null=True, upload_to=project.models.submission_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="payment_receipt",
            field=models.FileField(
                null=True, upload_to=project.models.submission_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="defense_application",
            name="revision_form",
            field=models.FileField(
                null=True, upload_to=project.models.submission_upload_path
            ),
        ),
    ]
