# Generated by Django 5.1 on 2025-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0108_alter_defense_application_adviser_confirmation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectgroupsettings",
            name="allow_defense_applications",
            field=models.BooleanField(default=True),
        ),
    ]
