# Generated by Django 5.1 on 2025-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0109_projectgroupsettings_allow_defense_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=120, null=True, verbose_name="Name"),
        ),
    ]
