# Generated by Django 5.1 on 2025-01-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0111_alter_defense_application_adviser_confirmation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
