# Generated by Django 5.1 on 2025-01-24 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0112_appuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="email_verification_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
