# Generated by Django 5.1 on 2025-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0113_appuser_email_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="deficiencies",
        ),
        migrations.AddField(
            model_name="appuser",
            name="remarks",
            field=models.CharField(blank=True, max_length=500, verbose_name="Remarks"),
        ),
    ]
