# Generated by Django 5.1 on 2025-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0114_remove_appuser_deficiencies_appuser_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
