# Generated by Django 5.1 on 2025-03-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0115_alter_appuser_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="name",
        ),
    ]
