# Generated by Django 5.1 on 2024-12-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0084_projectphase_first_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Defense_schedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.defense_application",
                    ),
                ),
            ],
        ),
    ]
