# Generated by Django 5.1 on 2024-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defense_schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defense_schedule",
            name="color",
            field=models.CharField(default="#FMXCFF", max_length=7),
        ),
    ]
