# Generated by Django 5.1 on 2025-01-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defense_schedule", "0002_alter_defense_schedule_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defense_schedule",
            name="title",
        ),
    ]
