# Generated by Django 5.1 on 2025-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defense_schedule", "0003_remove_defense_schedule_title"),
        ("project", "0091_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="defense_schedule",
            name="panel_members",
            field=models.ManyToManyField(
                blank=True, related_name="defense_schedules", to="project.faculty"
            ),
        ),
    ]
