# Generated by Django 5.1 on 2024-12-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="available_schedule",
            name="all_day",
            field=models.BooleanField(default=False),
        ),
    ]
