# Generated by Django 5.1 on 2024-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0003_available_schedule_all_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="available_schedule",
            name="all_day",
        ),
    ]
