# Generated by Django 5.1 on 2024-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0004_remove_available_schedule_all_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="available_schedule",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=7),
        ),
    ]
