# Generated by Django 5.1 on 2024-12-12 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0005_available_schedule_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="available_schedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
