# Generated by Django 5.1 on 2025-03-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0006_available_schedule_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="available_schedule",
            name="title",
        ),
    ]
