# Generated by Django 5.1 on 2025-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0007_remove_available_schedule_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="available_schedule",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
