# Generated by Django 5.1 on 2025-03-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("free_schedule", "0008_available_schedule_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="available_schedule",
            name="title",
        ),
    ]
